#!/bin/bash

## Description: Run phpcs inside the web container
## Usage: phpcs [flags] [args]
## Example: "ddev phpcs" or "ddev phpcs -n"
## ExecRaw: true

phpcs -s --report-full --report-summary  --ignore=*/.ddev/* "$@"
