#!/bin/bash

## Description: Restore SQLite database from a dump file
## Usage: sqlite:restore [source]
## Example: sqlite:restore /tmp/dump.txt

sqlite3 $BSKY_SQLITE_DATABASE "DROP TABLE IF EXISTS $BSKY_SQLITE_TABLE"
sqlite3 $BSKY_SQLITE_DATABASE < "$1"
